name: 'Discord Announcement Embeds'
author: 'michaellambgelo'
description: 'Send a scheduled message to Discord via webhook.'

inputs:
  webhook-url:
    description: 'Discord webhook URL.'
    required: true
  msg-content:
    description: 'Message content for the webhook.'
    required: true
  embed-color:
    description: "Embed color (hex)."
    required: false
    default: '65535'
  footer-icon:
    description: 'Icon URL for the footer (default: GitHub Mark).'
    required: false
    default: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
  scheduled-time:
    description: 'Date and time for the notification (YYYY-MM-DD HH:MM).'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Cron Expression
      id: cron
      run: |
        CRON_EXPRESSION=$(date -d "${{ inputs.scheduled-time }}" '+%M %H %d %m *')
        echo "CRON_EXPRESSION=$CRON_EXPRESSION" >> $GITHUB_ENV
      shell: bash
      
    - name: Prepare Announcement Embed
      id: prepare_embed
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_CREATOR="${{ github.event.issue.user.login }}"
        echo "ISSUE_TITLE=$ISSUE_TITLE" >> $GITHUB_OUTPUT
        echo "ISSUE_CREATOR=$ISSUE_CREATOR" >> $GITHUB_OUTPUT
      shell: bash

    - name: Send to Discord
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ inputs.webhook-url }}
        method: 'POST'
        data: |
          {
            "content": "${{inputs.msg-content}}",
            "embeds": [{
              "title": "${{ steps.prepare_embed.outputs.ISSUE_TITLE }}",
              "description": "${{ env.ANNOUNCEMENT_CONTENT }}",
              "color": ${{ inputs.embed-color }},
              "footer": {
                "text": "Created by ${{ steps.prepare_embed.outputs.ISSUE_CREATOR }}",
                "icon_url": "${{ inputs.footer-icon }}"
              },
              "timestamp": "${{ steps.get_time.outputs.time }}"
            }]
          }
